obj-$(CONFIG_INFINIBAND_SCIF) += ibscif.o

ibscif-y :=	ibscif_main.o		\
		ibscif_ah.o		\
		ibscif_pd.o		\
		ibscif_cq.o		\
		ibscif_qp.o		\
		ibscif_mr.o		\
		ibscif_cm.o		\
		ibscif_post.o		\
		ibscif_procfs.o		\
		ibscif_loopback.o	\
		ibscif_provider.o	\
		ibscif_protocol.o	\
		ibscif_scheduler.o	\
		ibscif_util.o
